My Project: sm.c File Reference
sm.c File Reference
#include <stdio.h>
Macros
#define NEXT(x, y, z) return ((void *)x)
Typedefs
typedef void *(* pF) (void)
Functions
void * led_on ()
void * led_off ()
void * led_save ()
void main ()
Variables
pF statefunc = led_on
pF oldfunc = NULL
Macro Definition Documentation
NEXT
#define NEXT (x, y, z) return ((void *)x)
Definition at line 6 of file sm.c.
Referenced by led_off(), led_on(), and led_save().
Typedef Documentation
pF
typedef void*(* pF) (void)
Definition at line 4 of file sm.c.
Function Documentation
led_off()
void * led_off ()
Turn off leds
Returns
led_on next_state
led_save next_state
Remarks
only to be called after start of ...
Definition at line 44 of file sm.c.
References led_on(), led_save(), and NEXT.
Referenced by led_on(), and led_save().
led_on()
void * led_on ()
Turn on leds
Returns
led_off next_state
Remarks
only to be called after start of ...
Definition at line 29 of file sm.c.
References led_off(), and NEXT.
Referenced by led_off(), and led_save().
led_save()
void * led_save ()
Sacve leds
Returns
led_on next_state
led_off next_state
Remarks
only to be called after start of ...
Definition at line 59 of file sm.c.
References led_off(), led_on(), and NEXT.
Referenced by led_off().
main()
void main ()
Definition at line 68 of file sm.c.
References oldfunc, and statefunc.
Variable Documentation
oldfunc
pF oldfunc = NULL
Definition at line 22 of file sm.c.
Referenced by main().
statefunc
pF statefunc = led_on
Definition at line 22 of file sm.c.
Referenced by main().